### ISSUE TITLE
Release updated modules: Percall, Chopping Kinky, Hexmix VCA, Kickall (v1.1.0 release)

### ISSUE THREAD

**Issue by hemmer** [VCVRack/Befaco#19]
Issue to track the work still to do before releasing the first new batch of modules. Preview below:

![image](https://user-images.githubusercontent.com/915048/114428304-ed712a80-9bb3-11eb-98c3-76788635bb68.png)

### Status

- Percall (90% done, just need to set/verify envelope times/shapes)
- Chopping Kinky (85% done, need to stress-test aliasing)
- Hexmix VCA (90% done, mainly verifying the shape against hardware)
- Kickall (60% done, wire in V/Oct correctly, wire in CV, calibrate with hardware)

### Outstanding issues

- [x] Calibrate and tune modules against hardware equivalents (and schematics) 
  - [x] Percall (envelope times)
  - [x] Chopping Kinky (waveshaper response) 
  - [x] Hexmix VCA (shape response)
  - [x] Kickall (tuning, CV summing logic, waveshaping, quite a bit!)
- [x] Update graphics with SVGs from Befaco
- [x] Check polyphony is implemented correctly
- [x] Code cleanup/documentation
- [x] Check performance is acceptable
- [x] Check aliasing ([Squinky Labs guide](https://github.com/squinkylabs/SquinkyVCV/blob/main/docs/aliasing.md))
- [x] Decide what to do about code re-use (currently using ChowDSP anti-aliasing code locally - need to discuss re-use, re-implementation etc)
- [x] Get feedback from Befaco
- [x] Get beta testers/feedback from VCV forums

### Possible additional issues
- [x] Merge / cleanup polyphony changes from https://github.com/martin-lueders/Befaco
- [x] Update input/output ports of all modules to use Befaco bananuts (makes parsing module more clear)

### Other
This is the fork where I am doing the work: https://github.com/hemmer/Befaco

**Comment by xustafu** [comment]
Percall envelope times, measured in the scope:

Attack time: 1.5 ms.
Minimum Decay time: Around 4.5 ms. (tolerance dependant on hardware)
Maximum Decay time: Around 4 seconds  (tolerance dependant on hardware)

**Comment by hemmer** [comment]
@xustafu - awesome thanks for the info. My plan is to get the hardware/software alongside each other in VCV (using ES-8) and also calibrate that way, but good to have those values as a sanity check.

**Comment by hemmer** [comment]
Now up and running for calibrating the modules. Today measuring the response of the wavefolder. Current progress for fitting the wavefolder shape to some rough analytical form is here:
* wavefolder a (synnmetric): https://www.desmos.com/calculator/5iww7nobjo
* wavefolder b (assymetric): https://www.desmos.com/calculator/yfnirdqda8

Idea will be to store in LUT. 

![image](https://user-images.githubusercontent.com/915048/120897437-10e9ac00-c61e-11eb-8952-80fd0a447234.png)

**Comment by AndrewBelt** [comment]
Wow, that looks pretty impressive. Have you considered the option of just using a wavetable with interpolation? Would probably be faster than evaluating a bunch of transcendental functions.

**Comment by hemmer** [comment]
Yeah definitely a job for pre-computing/wavetable. I just wanted to get the rough functional form to be able to render it out. It's interesting that both sections invert in the linear/near-zero region - it means if you want to waveshape a envelope or something you might want to invert first.

**Comment by hemmer** [comment]
Announcement thread here: https://community.vcvrack.com/t/new-befaco-modules/13624

**Comment by hemmer** [comment]
PR merged, submitted to VCV library for update: https://github.com/VCVRack/library/issues/684

**Comment by hemmer** [comment]
Now in the library. :)
