### ISSUE TITLE
Different ranges of C1 and C2 level in ABC

### ISSUE THREAD

**Issue by martin-lueders** [VCVRack/Befaco#2]
Is it intended behaviour that the output of the first A+B*C section only goes to 9.72 when no input is selected and C1 level is full right (or -9.72 when full left), while the second section goes from -10 to 10?

Cheers,
Martin

**Comment by AndrewBelt** [comment]
Looks like a typo.

**Comment by AndrewBelt** [comment]
Fixed in 014fce14d9b1c1f38608b7dc296fc05fb75718c7 a few days ago, forgot to close.
