### ISSUE TITLE
Spring reverb level label typo

### ISSUE THREAD

**Issue by jpnielsen** [VCVRack/Befaco#24]
https://github.com/VCVRack/Befaco/blob/5141e4ce45cb9084702fdee856c44543b235cb77/src/SpringReverb.cpp#L53

Should be:

```
		configParam(LEVEL2_PARAM, 0.0, 1.0, 0.0, "In 2 level", "%", 0, 100);

```

**Comment by AndrewBelt** [comment]
Thanks, fixed in 6d90388
