### ISSUE TITLE
Muxlicer clock in delayed sync

### ISSUE THREAD

**Issue by armandvedel** [VCVRack/Befaco#25]
I tried syncing two muxlicers, cabling the clock out of one into the clock in of another. The problem is that when I compare the all gates out of the two modules, it seems to take 3 clock pulses for the slave module to start sending gates. 

(for clarity, this is also the case with any clock module clocking the muxlicer)

**Comment by hemmer** [comment]
So it will take at least two in order to determine the clock speed (as it needs to measure). Do you have a screenshot of the setup just so I can be sure what you mean?

**Comment by armandvedel** [comment]
Oh! I don't have the hardware and assumed it would start right away with a gate to the clock in. So clock in goes to tap tempo? Here is a screenshot showing how the Muxlicer takes several clock ticks to start. In this case the red is the BPM clock and blue the Muxlicer. It took 3 pulses to start.

<img width="680" alt="Screen Shot 2021-11-05 at 12 19 54 PM" src="https://user-images.githubusercontent.com/39555156/140503187-6c5af0d6-c278-401e-a936-b38ccbffff3a.png">

**Comment by hemmer** [comment]
Yeah exactly, Muxlicer is effectively continuously using clock in as a tap tempo. You can even see this in the hardware version, see below (clock out/gates out should be similar behaviour): 

![image](https://user-images.githubusercontent.com/915048/140508891-efe0b5c2-684e-4280-baeb-87c4a080fcd1.png)

It sort of needs to work this way to implement clock mult/div unfortunately.

**Comment by armandvedel** [comment]
Thank you for the detailed response! And for the modules!
