### ISSUE TITLE
Muxlicer "All in Normalled Value" not changing after menu selection

### ISSUE THREAD

**Issue by lannzach** [VCVRack/Befaco#27]
Hi all,

I'm quite excited by the Muxlicer addition; however, the menu option for "All in Normalled Value" doesn't appear to be changing when different voltage levels are selected. I'll probably take a look in the code when I have some time, but if anyone knows a quick fix, I'd be super appreciative!

**Comment by armandvedel** [comment]
It works over here, at least I think so. You have to have nothing plugged into the all in.

**Comment by hemmer** [comment]
Yeah, here's me changing it, seems to work as expected: 

![image](https://user-images.githubusercontent.com/915048/140789911-82e50838-9f50-482f-94cc-d99b493c6549.png)

Feel free to re-open if you spot something else though!
