### ISSUE TITLE
Invalid tag in plugin.json

### ISSUE THREAD

**Issue by cschol** [VCVRack/Befaco#28]
@hemmer, I am not sure why this slipped through in the `v1` review, but we should fix this for `v2`:

```
[Befaco] Issues found in `plugin.json`:
                                                                             
STMix: invalid module tags: Stereo
-- Valid tags are defined in https://raw.githubusercontent.com/VCVRack/Rack/v2/src/tag.cpp
```

Thanks.

**Comment by hemmer** [comment]
Good catch, I also have a trivial fix for Muxlicer Tap Tempo, just wondering if @AndrewBelt  is happy that the `v2-redesign` branch can be merged back to the general `v2` so that these final cleanup pieces can be done on `v2`?

**Comment by cschol** [comment]
FYI, `v2-redesign` has been merged to `v2` as far as I can tell.

**Comment by hemmer** [comment]
Fixed in https://github.com/VCVRack/Befaco/commit/9a2a2a8f82c3ec9f6eb86c677ff8ba4e7e4aa495
