### ISSUE TITLE
Release Noise Plethora (v2.1.0 release)

### ISSUE THREAD

**Issue by hemmer** [VCVRack/Befaco#29]
Issue to track the work still to do before releasing Noise Plethora

![image](https://user-images.githubusercontent.com/915048/144379680-06d1a0a4-616d-4b87-a231-c9d1dafd6105.png)

**Outstanding issues**

- [x] add DC removal option
- [x] fixing playability of gritty noise
- [x] making sure results are sample rate invariant (Teensy assumes 44.1kHz, I’ve tried to address this so far)
- [x] port tooltips UI etc
- [x] Code cleanup/documentation
  - [x] use `onAction()` for knob pressess
- [x] Remove debug messages
- [x] Check performance is acceptable
- [x] Check aliasing/DC offsets (Squinky Labs guide)
- [x] Get feedback from Befaco
- [x] Get feedback from Andrew
- [x] Get beta testers/feedback from VCV forums
- [x] Update changelog and push release to library

**Builds / other**

This is the fork where I am doing the work: https://github.com/hemmer/Befaco (branch `v2-noise-plethora`).

**Comment by tastez** [comment]
@hemmer hi, just playing around with it and wondering if the behavior for the program selection is behaving like the hardware - it seems very odd, like the program selection knob acts as an offset to the incoming cv. In case this is as expected please ignore, otherwise i can look deeper.

**Comment by hemmer** [comment]
@tastez - I agree the behaviour was not quite correct. I've since discovered the infinite knob mode which is actually what the hardware uses - I've pushed a fix / build that hopefully addresses this.

**Comment by tastez** [comment]
thats great to hear! can't wait to test it 🎉

**Comment by tastez** [comment]
@hemmer  just tested it and incoming cv sequences don't seem to consistently set the values for the program knob still. Endless knob is great though

**Comment by hemmer** [comment]
OK I understand. My hardware unit doesn't do this either, but I wonder if that makes more sense than current setup? Currently if CV increases by 0.5V it increments, then resets the reference point (same for decrements).

**Comment by tastez** [comment]
ah interesting, was hoping program can be changed via cv but doesn't readjust reference points. To be able to use the knob as an offset does seem logical and nice. End goal imo should be repeatable sequences via cv in. Not familiar with the hardware or the logic there for cv input. Does that mean cv input range should always be less than -/+0.5?

**Comment by hemmer** [comment]
I tried with the hardware muxlicer into Noise PLethora and it doesn't play a consistent sequence. However I think that it makes more sense if it does, and I agree about repeatable sequences. I've pushed a new build that provides this functionality. It'd be great if you can test this (and try to break it).


https://user-images.githubusercontent.com/915048/156815381-5dfbf120-79b6-4e22-849b-1a8df470ad4e.mp4

**Comment by tastez** [comment]
🕺

**Comment by tastez** [comment]
one thing i found is that the endless program selector knob acts as a relative knob - i assume this is like the hardware.
you adjust the knob while on program A, set it to something like program 5, click the knob - program B is still at 0, regardless of the knob position and if you turn it clock wise to program 5 and then click it to adjust program A - program A would still be at program 5.

with the new experimental feature you've added (which is awesome imo), it seems the knob works in absolute mode - so if you have a sequence going into program A, the program select knob acts as an offset (nice) - however, clicking it and switching to select program B to something like 5 and clicking it again, will immediately apply the offset to program A's sequenced position. It is probably a headache to fix but could be a bit more logical.

*note - if nothing is plugged into program B, the knob still acts in relative mode - so adjusting an offset to a sequenced program A, and switching to program B, won't immediately set program B to a value.

** investigated a bit more and  it seems as long as your selector knob is on the program that you are feeding CV to, you can apply an offset to it - once you switch to adjust program select or bank select of the other oscillator, offset is removed from the other oscillator that has an incoming cv sequence.

**Comment by hemmer** [comment]
I understand. I spent quite a while trying to fix this, ended up copying the Plaits model where the module has a "state" that can be temporarily modified by CV. In this way, the program dial can be used to dial in a permenant offset to either bank, which then sums with CV. 

It can be a little confusing to understand what's going on, so I've made the LED darken a little when CV is present to help indicate: 


https://user-images.githubusercontent.com/915048/156945850-1250f5ba-c771-4458-b17b-1dd8d5754da8.mov

Let me know if this makes sense.

**Comment by tastez** [comment]
this is fantastic and the added led dimming is a great idea. Tried a few things and it is working flawlessly so far. Will try to break it more but awesome work.

**Comment by dromer** [comment]
Why not do it the other way around? Dim the led when not connected and brighten it when active?

Seems more intuitive to me anyway :)

**Comment by hemmer** [comment]
I've changed as you suggest @dromer (great shout), and merged back the PR to VCVRack/Befaco.

Submitted to the library here: https://github.com/VCVRack/library/issues/684#issuecomment-1062083168

**Comment by hemmer** [comment]
Now available in the library.
