### ISSUE TITLE
[bug] visual: slider graphics are misplaced

### ISSUE THREAD

**Issue by phdsg** [VCVRack/Befaco#3]
OS: win7 64bit
Rack: dev

see attached screenshot:
![befaco_sliderbug](https://user-images.githubusercontent.com/33329578/32655996-59319b06-c610-11e7-8903-4e9693d15a00.PNG)

rampage and the reverb too.

**Comment by AndrewBelt** [comment]
Fixed in 45d664a of Rack repo.
