### ISSUE TITLE
pulse wave has a huge amount of DC on it

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Befaco#36]
It's debatable, but I think most ppl don't want a "audio frequency" pulse wave to be DC coupled.

![image](https://user-images.githubusercontent.com/16314838/180497964-50673b35-15a3-493c-8094-d1e46efa5575.png)

**Comment by hemmer** [comment]
THanks for the report. I think it's _probably_ not desirable, but it is at least [representative of the hardware](https://youtu.be/16evcVXmKjU?t=103). If this is fixed, I suggest it's done as a context menu option (default disabled). You do get qualitatively different results (e.g. audio rate PM, FM something else). 

You can remove it arithmetically or by filter, how would you approach this?

**Comment by squinkylabs** [comment]
In my VCOs I compensate for the DC, just like I do with the DC added by the minBLEP saw. I reported this "bug" to Bogaudio and they fixed it last year. (so, yeah, algorithmically. I think I basically subtract out the pulse width?)

It is true that there are LFO uses where you do want the DC, but in general I hear so many VCV recordings with unintentional pops...

For more on DC: https://github.com/squinkylabs/Demo/blob/main/docs/dc.md

**Comment by hemmer** [comment]
HOping to merge this fix back soon!

https://github.com/hemmer/Befaco/commit/ecf835fa629e173bcb2b8dca273df8641af7e0c9#diff-472081787c8ad26eb4b8712029553b2ba85aee31499653dddd25b359401c2c22
