### ISSUE TITLE
Sawtooth wave has DC at high frequencies.

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/Befaco#37]
I think the VCV minblep code has a DC offset. I used to subtract it out in my VCOS.

![image](https://user-images.githubusercontent.com/16314838/180498197-f08fe71e-41d0-4a26-ab6b-b13eb4cd40dd.png)

**Comment by hemmer** [comment]
Should be fixed in the next release

![image](https://user-images.githubusercontent.com/915048/195038030-cd7e6b5e-32df-4e89-b845-ea7448139556.png)
