### ISSUE TITLE
Stereo Strip CPU increases by 600% while dragging EQ sliders

### ISSUE THREAD

**Issue by Yzrsah** [VCVRack/Befaco#39]
Stereo Strip, CPU shoots way up while dragging the EQ sliders

**Comment by hemmer** [comment]
Mm I see that it goes from 2% to ~5% on my machine, a 250% increase to be fair. I can't get anywhere near 600% though. Also it's a bit inevitable as a load of filter coefficients have to be recalculated. The only real fix is making the sliders slightly less responsive (e.g. only update the filters every N samples). I'll take a look but not sure we want to do that.

**Comment by Yzrsah** [comment]
@hemmer Thank you for looking into this. I'm running 96 kHz 64 samples, I checked and it looks like using low sample rates and large buffer sizes reduces the variance closer to the 2.5X.

**Comment by hemmer** [comment]
I think there's a tradeoff that should reduce CPU without a noticable effect, will add to the next release.
