### ISSUE TITLE
PonyVCO. Output goes to 'nanV' while FM'ing at sample rates of 192 or 768 kHz.

### ISSUE THREAD

**Issue by stnslvk** [VCVRack/Befaco#40]
In case 'Filter TZFM DC' option is enabled, PonyVCO's output goes to 'nanV' while FM'ing at sample rates of 192 or 768 kHz.

### To reproduce

* Rack Engine SR is to 192 or 768 kHz
* PonyVCO's 'Filter TZFM DC' option is enabled
* Feed some voltages to 'TZ FM'
### Outcome
PonyVCO's output goes to nanV

There is no issue in case Rack operates at sample rates other than 192 or 768 kHz.

Rack Engine SR is to 48 kHz  - ok
Rack Engine SR is set to 176.4 kHz - ok
Rack Engine SR is to 192 kHz - issue
Rack Engine SR is to 352.8 kHz - ok
...
Rack Engine SR is to 768 kHz or higher - issue

```
Win 10
PonyVCO 2.3.0
Rack Free Standalone 2.2.1
```

![2022-12-13_034446](https://user-images.githubusercontent.com/95583871/207198980-b291eec0-e033-4093-b1c0-e955096793a4.png)

![2022-12-13_034651](https://user-images.githubusercontent.com/95583871/207199006-6ffbea44-3a1e-40e3-b0cf-bd5d8c7878f4.png)

![2022-12-13_034738](https://user-images.githubusercontent.com/95583871/207199025-8a775ddd-fc98-4ac0-8489-bb4401d63609.png)

**Comment by hemmer** [comment]
Thanks for the report, I can reproduce and will take a look at some point. Quite a confusing bug though!

**Comment by hemmer** [comment]
Ah I think it's the TZFM DC blocker blowing up, as a workaround until this is fixed - if you disable this from the menu, does the issue go away?

**Comment by stnslvk** [comment]
Hi Ewan, thanks for looking into this.
Correct, the issue occurs only if 'Filter TZFM DC' option is enabled - forgot to mention this in the description.

Also, please have a look into 'Timber' behavior. With the same conditions, PonyVCO output goes to 'nanV' when it set to the max (1) value.

**Comment by hemmer** [comment]
No problem - could you clarify your second point there with a picture? I can't reproduce _that_ so far.

**Comment by stnslvk** [comment]
Interesting, cannot reproduce that on a freshly added PonyVCO instance either. Maybe there was some additional steps i took earlier .
Will provide additional info a bit later.

**Comment by stnslvk** [comment]
Further related findings are here #41

**Comment by hemmer** [comment]
I think the DC filter is unstable - it uses normalised frequencies so 5Hz / 192kHz is just too small a normalised filter frequency to be used. I switched to RCFilter which is stable even at those rates. There are new builds, can you confirm that this fixes things for you?

**Comment by stnslvk** [comment]
At first sight the issue is addressed.
There are no more 'NanV' at output.
Happy to close this one.
Ewan, thank you.
