### ISSUE TITLE
PonyVCO produces wobbling pitch after 'TZ FM' source disconnection.

### ISSUE THREAD

**Issue by stnslvk** [VCVRack/Befaco#41]
The issue occurs only if PonyVCO's 'Filter TZFM DC' option is enabled.

### To reproduce

* Rack Engine SR is set to other frequencies than 192 or 768 kHz (please refer to #40 )
* PonyVCO's 'Filter TZFM DC' option is enabled
* Feed some voltages to 'TZ FM'
* Then disconnect  'TZ FM' source

### Outcome
PonyVCO produces wobbling pitch after 'TZ FM' source disconnection.

After these steps there is additional step that leads to 'nanV' volts at output.
Just set Rack Engine SR to 192 or 768 kHz and touch the 'Timber' slider.

Please refer to the attached video for the details.

```
Win 10
PonyVCO 2.3.0
Rack Free Standalone 2.2.1
```
https://user-images.githubusercontent.com/95583871/207473265-460d0971-e12d-4ec6-be00-31bcebb4e5c6.mp4

**Comment by hemmer** [comment]
I was using a Butterworth filter to not interfere with the frequency response, but it does produce ripples [1] in impulse repsonse. The hardware doesn't do this, so I've switched to the RC Filter which should just slide monotonically now. 

[1] https://dsp.stackexchange.com/questions/63780/butterworth-filter-transfer-function-in-time-domain

**Comment by stnslvk** [comment]
Ewan. thanks for bts regarding these wobbles.

With the latest build I cannot hear those noticeable wobbles in pitch.
Happy to close this one.
Ewan, thank you.
