### ISSUE TITLE
Trigg Out is == Clock Out in INTERNAL clock mode

### ISSUE THREAD

**Issue by LOGUNIVPM** [VCVRack/Befaco#50]
Like the object says: the trigger out is identical to the clock out when in internal clock mode. The clock out fires a 50% duty cycle square wave based on the BPM and the trigger out should output short pulses, instead it fires exactly the same output as the clock out. I don't know if this is the intended behavior but it sounds strange. In external clock mode it correctly fires pulses.

**Comment by hemmer** [comment]
Which module is this for?

**Comment by hemmer** [comment]
But if it's sampling modulator see here: https://github.com/VCVRack/Befaco/issues/26#issuecomment-961835255

**Comment by LOGUNIVPM** [comment]
Oops, I forgot to say, yes, it's the sampling modulator.
I see, the choice is between breaking perfect replicability of the hardware or getting a correct trigger pulse, and of course the former is more important. I'd say that most VCV modules should work with the trigger pulse even if it's not 1ms long because they should use the SchmittTrigger object to detect the rising edge. Hopefully.
