### ISSUE TITLE
Emulated or sampled

### ISSUE THREAD

**Issue by MC242** [VCVRack/Befaco#51]
I have a question about the way that hardware is ported to VCV.
Shortly ago, I tested Befaco Noise Plethora in VCV Rack. I started with algorithm 1 on the left side and shortly after that I connected algorithm 2 with the same sound on the right side.
I discovered that the noise sounds had some characteristics and artifacts I heard on the left side, which then repeated on the right side all the time exactly the same. Like a ping-pong delay. Does this mean that this module is only sampled instead of emulated?

**Comment by hemmer** [comment]
Hi! I'm not sure I understand the question or the distinction between sampled and emulated? But anyway on the hardware, a teensy generates the noise sources and in software the exact same code is used so those should be the same (emulated?). The filters on software are only an approximation to hardware filters, so will sound slightly different. 

As for delay like effect, some noise sources are actually periodic (i.e. repeating) but just complex (e.g. loads of FM). So if the left and right are the same algorithm, but started off at different times, you will maybe hear a phasing effect between the two. This is neither a feature nor a bug, just life :)

**Comment by MC242** [comment]
Hallo Evan! Thank you very much for the explanation. I‘m not really sure what is happening, but maybe you can try it yourself with the Noise Plethora. Cheers, Michelle.Am 04.09.2024 um 09:42 schrieb Ewan ***@***.***>:﻿
Hi! I'm not sure I understand the question or the distinction between sampled and emulated? But anyway on the hardware, a teensy generates the noise sources and in software the exact same code is used so those should be the same (emulated?). The filters on software are only an approximation to hardware filters, so will sound slightly different.
As for delay like effect, some noise sources are actually periodic (i.e. repeating) but just complex (e.g. loads of FM). So if the left and right are the same algorithm, but started off at different times, you will maybe hear a phasing effect between the two. This is neither a feature nor a bug, just life :)
