### ISSUE TITLE
Noise Plethora knobs mis-labeled

### ISSUE THREAD

**Issue by gabriel-roth** [VCVRack/Befaco#53]
This is about the labels that appear in a tooltip when I hover my mouse cursor over a knob — this same text string is used when mapping a Meta Module knob to a knob on a module. 

On the Noise Plethora, the Cutoff B knob is labeled "Cutoff CV B" and the Cutoff CV B knob is labeled "Cutoff B." (Again, I'm not referring to the labels on the panel of the module — I'm talking about the internal parameter names that show up on the tooltips.)

**Comment by hemmer** [comment]
Good catch, a fix will make it into the next release(s)

**Comment by hemmer** [comment]
Fixed in v2.8.0
