### ISSUE TITLE
Slew Limiter: cv input sensitivity

### ISSUE THREAD

**Issue by phdsg** [VCVRack/Befaco#7]
i find the cv inputs on the slew limiter kind of hard to work with as they only operate so well in a [0..1]V range.
is that intended behavior?
anyways, i scaled down the inputs on my local clone and it feels much more usable that way.

**Comment by AndrewBelt** [comment]
Thanks! Fixed in 8e6db52c136a37f9e7545ab6db6143f46bcc27e7
