### ISSUE TITLE
build fail with Rack master

### ISSUE THREAD

**Issue by davephillips** [VCVRack/Befaco#8]
Fedora 23 Linux
Rack master (0.6.x)

Hi Andrew, I assume you already know this. The same is true (similar errors) for the ESeries and Audible Instruments repos. Please advise if the fix is simple. :)

[dlphilp@The6300 Befaco]$ make
g++ -Wsuggest-override -std=c++11 -I./pffft -DPFFFT_SIMD_DISABLE -fPIC -I../../include -I../../dep/include -DSLUG=Befaco -DVERSION=0.6.0dev -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/SpringReverb.cpp.o src/SpringReverb.cpp
src/SpringReverb.cpp: In constructor ‘SpringReverbWidget::SpringReverbWidget()’:
src/SpringReverb.cpp:266:40: error: no matching function for call to ‘rack::ModuleWidget::ModuleWidget()’
 SpringReverbWidget::SpringReverbWidget() {
                                        ^
In file included from ../../include/rack.hpp:9:0,
                 from src/Befaco.hpp:1,
                 from src/SpringReverb.cpp:2:
../../include/app.hpp:63:2: note: candidate: rack::ModuleWidget::ModuleWidget(rack::Module*)
  ModuleWidget(Module *module);
  ^
../../include/app.hpp:63:2: note:   candidate expects 1 argument, 0 provided
In file included from ../../include/rack.hpp:9:0,
                 from src/Befaco.hpp:1,
                 from src/SpringReverb.cpp:2:
../../include/app.hpp:53:8: note: candidate: rack::ModuleWidget::ModuleWidget(const rack::ModuleWidget&)
 struct ModuleWidget : OpaqueWidget {
        ^
../../include/app.hpp:53:8: note:   candidate expects 1 argument, 0 provided
src/SpringReverb.cpp:268:18: error: ‘setModule’ was not declared in this scope
  setModule(module);
                  ^
../../compile.mk:56: recipe for target 'build/src/SpringReverb.cpp.o' failed
make: *** [build/src/SpringReverb.cpp.o] Error 1

**Comment by AndrewBelt** [comment]
https://github.com/VCVRack/community/issues/269#issuecomment-365812899
